name: aund smoke test
on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  linux-build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: regenerate autoconf
      run: autoreconf -fiv .
    - name: configure
      run: ./configure
    - name: configure
      run: ./configure
    - name: make
      run: make
    - name: make distcheck
      run: make distcheck
  macos-build:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v4
    - name: regenerate autoconf
      run: autoreconf -fiv .
    - name: configure
      run: ./configure
    - name: configure
      run: ./configure
    - name: make
      run: make
